version: 1
update_configs:
  - package_manager: javascript
    directory: "/"
    update_schedule: live
    automerged_updates:
      - match:
          dependency_name: "@types/*"
      - match:
          dependency_name: "@fortawesome/fontawesome-free"
      - match:
          dependency_name: babel-plugin-relay
      - match:
          dependency_name: bootstrap
      - match:
          dependency_name: prettier
